version: '3.8'

services:
  mc-server:
    build: .
    container_name: mc-server
    environment:
      - TAILSCALE_AUTH_KEY=${TAILSCALE_AUTH_KEY}
      - MC_SERVER_NAME=${MC_SERVER_NAME}
      - MC_MAX_PLAYERS=${MC_MAX_PLAYERS}
      - BACKUP_INTERVAL=${BACKUP_INTERVAL}
    volumes:
      - /Users/IanSpresney/Desktop/MCBackups:/app/backups
    ports:
      - "19132:19132/udp"
    restart: always