version: '3'

services:
  minecraft:
    build: .
    container_name: minecraft-bedrock-server
    ports:
      - "19132:19132/udp"
    environment:
      - TAILSCALE_AUTH_KEY=${TAILSCALE_AUTH_KEY}
    network_mode: "host"  # Use host network mode to allow Tailscale to manage network traffic
    volumes:
      - ./bedrock-server-1:/app/bedrock-server-1
      - ~/Desktop/Minecraft-Backups:/app/backups  # Mount local backup folder to container
    restart: unless-stopped